// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>
#import <AudioToolbox/AudioToolbox.h>
#import <AudioUnit/AudioUnit.h>
#import <CFNetwork/CFNetwork.h>
#import <CoreAudio/CoreAudio.h>
#import <CoreData/CoreData.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import <Security/Security.h>
#import <CFNetwork/CFNetwork.h>
#import <Cocoa/Cocoa.h>
#import <QTKit/QTKit.h>
#import <Quartz/Quartz.h>
#import <AVFoundation/AVFoundation.h>

@interface AppDelegate: NSObject <NSApplicationDelegate>
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) open_prefs_window:(id) sender;
-(IBAction) buildPrefsWindow;
-(IBAction) buildMaskWindow;

@end

@interface ScreenSaverWindowController: NSWindowController
-(IBAction) setup_window:(id) video;
-(IBAction) video_play:(id) item;
-(IBAction) send_command:(id) command;
-(IBAction) playerItemDidReachEnd:(id) notification;
-(IBAction) hide_window;
-(IBAction) show_window;

@end

@interface PreferenceController: NSWindowController
-(IBAction) init;
-(IBAction) setupDefaults;
-(IBAction) savePrefs:(id) sender;
-(IBAction) savePrefsAndCloseWindow:(id) sender;
-(IBAction) showWindow:(id) sender;
-(IBAction) closeWindow:(id) sender;
-(IBAction) open_folder:(id) sender;
-(IBAction) update_preferences;

@end

@interface MaskWindowController: NSWindowController

@property IBOutlet NSButton * button;

-(IBAction) init;
-(IBAction) test_cmd;
-(IBAction) show_window;
-(IBAction) windowDidLoad;

@end

@interface EosCursorHider: NSObject
-(IBAction) hide_cursor;
-(IBAction) show_cursor;
-(IBAction) hide_loop;
-(IBAction) activate_app;
-(IBAction) cursor_hide_toggle;

@end

