// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation ScreenSaverWindowController
@end

@implementation PreferenceController
@end

@implementation MaskWindowController
@end

@implementation EosCursorHider
@end

